---------------------------------------
(flaskEnv) C:\Users\sbishop7\Desktop\python_stack\flask_MySQL\friends>python server.py
Traceback (most recent call last):
  File "server.py", line 4, in <module>
    mysql = MySQLConnector(app,'friendsdb')
  File "C:\Users\sbishop7\Desktop\python_stack\flask_MySQL\friends\mysqlconnection.py", line 40, in MySQLConnector
    return MySQLConnection(app, db)
  File "C:\Users\sbishop7\Desktop\python_stack\flask_MySQL\friends\mysqlconnection.py", line 9, in __init__
    'database': databass, # we got db as an argument
NameError: global name 'databass' is not defined

FIX:  Change database name back to 'db'

---------------------------------------

OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'groot'@'localhost' (using password: YES)")

FIX: change user back to 'root'

---------------------------------------

OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

FIX: change password back to 'root'


---------------------------------------

OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (10061)")

FIX:  change the port back to '3306'

---------------------------------------

